ci: update github hooks

diff --git a/.git-hooks/pre-push b/.git-hooks/pre-push
--- a/.git-hooks/pre-push
+++ b/.git-hooks/pre-push
@@ -6,14 +6,22 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
-# check if any changes are not committed
-if [[ -n $(git status --porcelain) ]]; then
-  echo "You have uncommitted changes. Please commit or stash them before pushing."
-  exit 1
-fi
 
 cargo sqlx prepare --workspace --check --all -- --all-targets --all-features
 if [ $? -ne 0 ]; then
 	echo "SQLx checks failed. Aborting push."
 	exit 1
+fi
+
+just test-all
+if [ $? -ne 0 ]; then
+	echo "Tests failed. Please fix the issues before pushing."
+	exit 1
+fi
+
+
+# check if any changes are not committed
+if [[ -n $(git status --porcelain) ]]; then
+  echo "You have uncommitted changes. Please commit or stash them before pushing."
+  exit 1
 fi
